# Generated by Django 4.2.4 on 2023-11-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('value', models.CharField(choices=[('urgente', 'Alto'), ('importante', 'Medio'), ('basico', 'Bajo')], max_length=20)),
                ('state', models.CharField(choices=[('proceso', 'En Curso'), ('terminado', 'Finalizado')], max_length=20)),
                ('evidence_documents', models.FileField(upload_to='documents/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('assigned_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_Task', to='comments_task.comments')),
            ],
        ),
    ]
