# Generated by Django 4.2.4 on 2023-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='evidence_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(),
        ),
    ]
