# Generated by Django 4.2.4 on 2023-11-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_task', '0001_initial'),
        ('tareas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_birthday', models.DateField()),
                ('rol_user', models.CharField(choices=[('client', 'Cliente'), ('Admin', 'Administrador'), ('editor', 'Editor')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('assigned_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_task.comments')),
                ('assigned_user', models.ManyToManyField(blank=True, related_name='users_assigned_tasks', to='tareas_app.tasks')),
            ],
        ),
    ]
