# Generated by Django 4.2.4 on 2024-01-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0003_alter_tasks_evidence_documents_and_more'),
        ('comments_task', '0002_initial'),
        ('user_app', '0002_alter_users_assigned_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='assigned_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_task.comments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='assigned_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_assigned_tasks', to='tareas_app.tasks'),
        ),
    ]
