# Generated by Django 4.2.4 on 2024-01-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_users_assigned_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_user',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
