# Generated by Django 4.2.4 on 2023-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('qualification', models.IntegerField(blank=True, null=True)),
                ('message_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
