# Generated by Django 4.2.4 on 2023-11-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_task', '0001_initial'),
        ('tareas_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='assigned_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tareas_app.tasks'),
        ),
        migrations.AddField(
            model_name='comments',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_app.users'),
        ),
    ]
